[FileDialog]
history=file:///home/shorin/\xc3\xa8\xc2\xa7\xc2\x86\xc3\xa9\xc2\xa2\xc2\x91, file:///home/shorin/\xe8\xa7\x86\xe9\xa2\x91, file:///home/shorin, file:///home/shorin/\x89c6\x9891, file:///home/shorin/\x56fe\x7247/Screenshots, file:///home/shorin/Pictures/Screenshots
lastVisited=file:///home/shorin/Pictures/Screenshots
qtVersion=5.15.14
shortcuts=file:, file:///home/shorin
sidebarWidth=111
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
